/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Answer = {
  _type: "answer";
  questionKey?: string;
  questionLabel?: string;
  values?: Array<string>;
};

export type QuestionOption = {
  _type: "questionOption";
  label?: string;
  value?: string;
};

export type Question = {
  _type: "question";
  label?: string;
  type?:
    | "text"
    | "textarea"
    | "radio"
    | "checkbox"
    | "select"
    | "boolean"
    | "rating";
  helpText?: string;
  required?: boolean;
  options?: Array<
    {
      _key: string;
    } & QuestionOption
  >;
};

export type Step = {
  _type: "step";
  title?: string;
  description?: string;
  questions?: Array<
    {
      _key: string;
    } & Question
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type TextWithImage = {
  _type: "textWithImage";
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h3";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  imagePosition?: "right" | "left";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & TextWithImage)
>;

export type QuestionnaireReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "questionnaire";
};

export type Submission = {
  _id: string;
  _type: "submission";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  questionnaire?: QuestionnaireReference;
  respondentName?: string;
  respondentEmail?: string;
  submittedAt?: string;
  answers?: Array<
    {
      _key: string;
    } & Answer
  >;
  reviewed?: boolean;
  notes?: string;
};

export type Questionnaire = {
  _id: string;
  _type: "questionnaire";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  steps?: Array<
    {
      _key: string;
    } & Step
  >;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: CategoryReference;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  order?: number;
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  body?: BlockContent;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
  author?: AuthorReference;
  publishedAt?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Answer
  | QuestionOption
  | Question
  | Step
  | SanityImageAssetReference
  | TextWithImage
  | BlockContent
  | QuestionnaireReference
  | Submission
  | Questionnaire
  | Slug
  | CategoryReference
  | Tag
  | Category
  | TagReference
  | AuthorReference
  | Post
  | Author
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: FILTER_GROUPS_QUERY
// Query: *[_type == "category"] | order(order asc, title asc) {    _id,    title,    "slug": slug.current,    "tags": *[_type == "tag" && references(^._id)] | order(title asc) {      _id,      title,      "slug": slug.current    }  }
export type FILTER_GROUPS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  tags: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }>;
}>;

// Source: sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)]  | order(coalesce(publishedAt, _createdAt) desc) {    _id,    title,    "slug": slug.current,    description,    publishedAt,    mainImage,      tags[]->{    _id,    title,    "slug": slug.current,    "categoryId": category._ref  },    "author": author->{ name, "slug": slug.current, avatar }  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  publishedAt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  tags: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    categoryId: string | null;
  }> | null;
  author: {
    name: string | null;
    slug: string | null;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    description,    publishedAt,    mainImage,    gallery,      tags[]->{    _id,    title,    "slug": slug.current,    "categoryId": category._ref  },    body,    "author": author->{ name, "slug": slug.current, avatar, bio }  }
export type POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  publishedAt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  gallery: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  tags: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    categoryId: string | null;
  }> | null;
  body: BlockContent | null;
  author: {
    name: string | null;
    slug: string | null;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    bio: string | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: LATEST_POST_QUERY
// Query: *[_type == "post" && defined(slug.current)]  | order(coalesce(publishedAt, _createdAt) desc, _createdAt desc)[0]{    _id,    title,    "slug": slug.current,    description,    publishedAt,    mainImage,      tags[]->{    _id,    title,    "slug": slug.current,    "categoryId": category._ref  },    "author": author->{ name, "slug": slug.current, avatar, bio }  }
export type LATEST_POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  publishedAt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  tags: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    categoryId: string | null;
  }> | null;
  author: {
    name: string | null;
    slug: string | null;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    bio: string | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: POSTS_LIST_QUERY
// Query: *[_type == "post" && defined(slug.current)]  | order(coalesce(publishedAt, _createdAt) desc, _createdAt desc)[1...10]{    _id,    title,    "slug": slug.current,    description,    publishedAt,    mainImage,      tags[]->{    _id,    title,    "slug": slug.current,    "categoryId": category._ref  },    "author": author->{ name, "slug": slug.current, avatar, bio }  }
export type POSTS_LIST_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  publishedAt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  tags: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    categoryId: string | null;
  }> | null;
  author: {
    name: string | null;
    slug: string | null;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    bio: string | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: POSTS_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{ "slug": slug.current }
export type POSTS_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: QUESTIONNAIRE_QUERY
// Query: *[_type == "questionnaire" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    description,    steps[]{      _key,      title,      description,      questions[]{        _key,        label,        type,        helpText,        required,        options[]{ label, value }      }    }  }
export type QUESTIONNAIRE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  steps: Array<{
    _key: string;
    title: string | null;
    description: string | null;
    questions: Array<{
      _key: string;
      label: string | null;
      type:
        | "boolean"
        | "checkbox"
        | "radio"
        | "rating"
        | "select"
        | "text"
        | "textarea"
        | null;
      helpText: string | null;
      required: boolean | null;
      options: Array<{
        label: string | null;
        value: string | null;
      }> | null;
    }> | null;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: DEFAULT_QUESTIONNAIRE_QUERY
// Query: *[_type == "questionnaire"] | order(_createdAt asc)[0]{    _id,    title,    "slug": slug.current,    description,    steps[]{      _key,      title,      description,      questions[]{        _key,        label,        type,        helpText,        required,        options[]{ label, value }      }    }  }
export type DEFAULT_QUESTIONNAIRE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  steps: Array<{
    _key: string;
    title: string | null;
    description: string | null;
    questions: Array<{
      _key: string;
      label: string | null;
      type:
        | "boolean"
        | "checkbox"
        | "radio"
        | "rating"
        | "select"
        | "text"
        | "textarea"
        | null;
      helpText: string | null;
      required: boolean | null;
      options: Array<{
        label: string | null;
        value: string | null;
      }> | null;
    }> | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "category"] | order(order asc, title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    "tags": *[_type == "tag" && references(^._id)] | order(title asc) {\n      _id,\n      title,\n      "slug": slug.current\n    }\n  }\n': FILTER_GROUPS_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]\n  | order(coalesce(publishedAt, _createdAt) desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    publishedAt,\n    mainImage,\n    \n  tags[]->{\n    _id,\n    title,\n    "slug": slug.current,\n    "categoryId": category._ref\n  }\n,\n    "author": author->{ name, "slug": slug.current, avatar }\n  }\n': POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    publishedAt,\n    mainImage,\n    gallery,\n    \n  tags[]->{\n    _id,\n    title,\n    "slug": slug.current,\n    "categoryId": category._ref\n  }\n,\n    body,\n    "author": author->{ name, "slug": slug.current, avatar, bio }\n  }\n': POST_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]\n  | order(coalesce(publishedAt, _createdAt) desc, _createdAt desc)[0]{\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    publishedAt,\n    mainImage,\n    \n  tags[]->{\n    _id,\n    title,\n    "slug": slug.current,\n    "categoryId": category._ref\n  }\n,\n    "author": author->{ name, "slug": slug.current, avatar, bio }\n  }\n': LATEST_POST_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]\n  | order(coalesce(publishedAt, _createdAt) desc, _createdAt desc)[1...10]{\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    publishedAt,\n    mainImage,\n    \n  tags[]->{\n    _id,\n    title,\n    "slug": slug.current,\n    "categoryId": category._ref\n  }\n,\n    "author": author->{ name, "slug": slug.current, avatar, bio }\n  }\n': POSTS_LIST_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]{ "slug": slug.current }\n': POSTS_SLUGS_QUERY_RESULT;
    '\n  *[_type == "questionnaire" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    steps[]{\n      _key,\n      title,\n      description,\n      questions[]{\n        _key,\n        label,\n        type,\n        helpText,\n        required,\n        options[]{ label, value }\n      }\n    }\n  }\n': QUESTIONNAIRE_QUERY_RESULT;
    '\n  *[_type == "questionnaire"] | order(_createdAt asc)[0]{\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    steps[]{\n      _key,\n      title,\n      description,\n      questions[]{\n        _key,\n        label,\n        type,\n        helpText,\n        required,\n        options[]{ label, value }\n      }\n    }\n  }\n': DEFAULT_QUESTIONNAIRE_QUERY_RESULT;
  }
}
